name: Deploy to Linode S3
on:
  push:
    branches: [main]

jobs:
  Frontend-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install dependencies
        run: yarn install

      - name: Run prettier format check
        run: yarn format:check

      - name: Run eslint check
        run: yarn lint:check

      - name: Build
        run: yarn build

      - name: Set up S3cmd 
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: linode 
          region: 'eu-central-1'
          access_key: ${{ secrets.LINODE_S3_ACCESS_KEY }}
          secret_key: ${{ secrets.LINODE_S3_SECRET_KEY }}

      - name: Interact with object storage
        run: |
          s3cmd sync --no-mime-magic --delete-removed --delete-after --acl-public dist/ s3://resurrectism.denismail.space

      - name: Get info
        run: s3cmd ws-info s3://resurrectism.denismail.space
