name: Format, Lint & Build 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Frontend-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install dependencies
        run: yarn install

      - name: Run prettier format check
        run: yarn format:check

      - name: Run eslint check
        run: yarn lint:check

      - name: Build
        run: yarn build
